### ISSUE TITLE
About the fanbeam

### ISSUE THREAD

**Issue by Mors20** [iwuqing/SCOPE#2]
Hi,

Thanks for your great work! And I'm trying to reproduce your work, I've been able to successfully replicate the part of parallel beam but it appears that there is no code available for fanbeam reconstruction. I'm quite interested in this aspect, and I'm wondering if you could provide the code for fanbeam reconstruction. I attempted to implement it on my own, but the results have been unsatisfactory. I'm not sure if there's a bug or some other issue causing the problem.

Best Regards

**Comment by iwuqing** [comment]
Thanks for your attention to our work. :) I can provide the code for fan-beam reconstruction. However, I have some pressing academic activities this month which may prevent me from refactoring the code and uploading it to GitHub until Dec. 1st.

**Comment by heeta0** [comment]
Hello, thank you for your excellent work. I am very interested in this aspect and hope to try replicating this project. But I found that the code is incomplete: there is no SCOPE. py file. I hope you can supplement the code completely. thanks:)

**Comment by iwuqing** [comment]
@heeta0 Hi~
I have updated the files SCOPE.py and dataset.py into the repo. :)

**Comment by 12345678901234567800001882277777** [comment]
> Hi,
> 
> Thanks for your great work! And I'm trying to reproduce your work, I've been able to successfully replicate the part of parallel beam but it appears that there is no code available for fanbeam reconstruction. I'm quite interested in this aspect, and I'm wondering if you could provide the code for fanbeam reconstruction. I attempted to implement it on my own, but the results have been unsatisfactory. I'm not sure if there's a bug or some other issue causing the problem.
> 
> Best Regards

Hello, I'm not sure if you can see this message, but I've been working on reproducing an experiment recently. However, I'm confused about the process of converting .png files to .nii format. I've been using the radon function to process 90 views of .png images, and then directly converting them into .nii format for training and re-projection. But the results are quite different from what was presented in the paper. I hope to hear back from you and learn about your implementation process. Thank you very much!
