### ISSUE TITLE
Replace Sigmoid with ReLU as the activate function of output layer might perform better

### ISSUE THREAD

**Issue by ILoveU3D** [iwuqing/SCOPE#3]
In my experiments, I found that using `ReLU` as activate the function of output layer might get better results, especially in more soft tissue scenes. With `Sigmoid`, the result shows more noise like Salt and Pepper. I guess it might be related to the grad explosion or disappearance in backward process.

**Comment by iwuqing** [comment]
Hi~ @ILoveU3D 
Sorry for the delay in my response.  I completely agree with your viewpoint on this experimental finding.  Thank you for sharing this interesting report!
